name: Crystal CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest}
          - {os: windows-latest}
    runs-on: ${{matrix.os}}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - run: crystal spec
      - run: crystal tool format --check
        if: matrix.crystal == 'latest'
